"""Generate an AML investigation summary via OpenAI, with a template fallback.

If ``OPENAI_API_KEY`` is set the summary is generated by the model; otherwise
(or on any API error) a deterministic, professional template is produced from
the structured evidence so the demo always works offline.
"""

from __future__ import annotations

import json
import logging

from app.ai.client import get_client
from app.ai.prompt import summary_messages
from app.core.config import settings

logger = logging.getLogger("sentinel.ai")

# Map rule codes to plain-language laundering behaviors.
BEHAVIOR = {
    "AML-01": "Structuring / smurfing (deposits kept below the $10k reporting threshold)",
    "AML-02": "Rapid pass-through / layering of funds",
    "AML-03": "Circular transfers among a ring of related accounts",
    "AML-04": "Reactivation of a long-dormant account with sudden large inflows",
    "AML-05": "High-velocity dispersion of funds",
    "AML-06": "Geographically impossible activity (card/account compromise)",
    "AML-07": "Money-mule collection from many unrelated senders",
    "AML-08": "Exposure to high-risk jurisdictions",
    "AML-09": "Large cash deposits",
    "AML-10": "Sudden high-volume activity on a newly opened account",
}

_REQUIRED_KEYS = {
    "executive_summary",
    "key_findings",
    "likely_behaviors",
    "risk_assessment",
    "recommended_next_steps",
}


def generate_investigation_summary(context: dict) -> dict:
    client = get_client()
    if client is not None:
        try:
            resp = client.chat.completions.create(
                model=settings.openai_model,
                messages=summary_messages(context),
                response_format={"type": "json_object"},
                temperature=0.3,
            )
            data = json.loads(resp.choices[0].message.content)
            if _REQUIRED_KEYS.issubset(data):
                data["generated_by"] = "openai"
                data["model"] = settings.openai_model
                return data
            logger.warning("OpenAI response missing keys; using template.")
        except Exception:  # noqa: BLE001
            logger.exception("OpenAI summary failed; using template.")
    return _template_summary(context)


def _template_summary(context: dict) -> dict:
    c = context["customer"]
    rules = context.get("rules", [])
    flagged = context.get("flagged_transactions", [])
    counts = context.get("counts", {})

    behaviors = [BEHAVIOR.get(r["code"], r["name"]) for r in rules]
    top_amount = max((t["amount"] for t in flagged), default=0.0)

    executive_summary = (
        f"{c['name']}, a {c['occupation']} based in {c['city']}, {c['country']}, "
        f"has been assigned a risk score of {c['risk_score']}/100 "
        f"({c['risk_level']}). The account relationship triggered "
        f"{len(rules)} AML rule(s) across {counts.get('total_flagged', 0)} "
        f"flagged transaction(s), consistent with "
        f"{behaviors[0].lower() if behaviors else 'anomalous activity'}."
    )

    key_findings = [
        f"{r['name']} ({r['code']}, +{r['points']} pts): {r['reason']}"
        for r in rules
    ]
    if flagged:
        key_findings.append(
            f"Largest flagged transaction: ${top_amount:,.0f}; "
            f"{counts.get('total_flagged', 0)} flagged transactions in total."
        )
    if c.get("is_high_risk_jurisdiction"):
        key_findings.append(
            f"Customer is associated with a high-risk jurisdiction ({c['country']})."
        )

    band = c["risk_level"]
    risk_assessment = {
        "critical": "Risk is CRITICAL. Multiple strong indicators of coordinated "
        "money laundering are present; immediate escalation is warranted.",
        "high": "Risk is HIGH. The pattern of activity is materially inconsistent "
        "with the customer's expected profile and merits formal investigation.",
        "medium": "Risk is MEDIUM. Activity shows notable anomalies that warrant "
        "enhanced monitoring and analyst review.",
        "low": "Risk is LOW. Limited indicators were detected; routine monitoring "
        "is advised.",
    }.get(band, "Risk assessment unavailable.")

    next_steps = [
        "Conduct Enhanced Due Diligence (EDD) on the customer and connected parties.",
        "Review the transaction network for additional linked accounts and mules.",
    ]
    if band in ("high", "critical"):
        next_steps.append(
            "Prepare and file a Suspicious Activity Report (SAR) with the FIU."
        )
        next_steps.append(
            "Consider placing a temporary hold / restriction pending review."
        )
    else:
        next_steps.append("Maintain enhanced transaction monitoring for 90 days.")

    return {
        "executive_summary": executive_summary,
        "key_findings": key_findings,
        "likely_behaviors": behaviors or ["Anomalous transaction activity"],
        "risk_assessment": risk_assessment,
        "recommended_next_steps": next_steps,
        "generated_by": "template",
        "model": None,
    }
