"""Generate an AML investigation summary via OpenAI, with a template fallback.

If ``OPENAI_API_KEY`` is set the summary is generated by the model; otherwise
(or on any API error) a deterministic, professional template is produced from
the structured evidence so the demo always works offline.
"""

from __future__ import annotations

import json
import logging

from app.ai.client import get_client
from app.ai.prompt import summary_messages
from app.core.config import settings

logger = logging.getLogger("sentinel.ai")

# Map rule codes to plain-language laundering behaviors.
BEHAVIOR = {
    "AML-01": "Structuring / smurfing (deposits kept below the $10k reporting threshold)",
    "AML-02": "Rapid pass-through / layering of funds",
    "AML-03": "Circular transfers among a ring of related accounts",
    "AML-04": "Reactivation of a long-dormant account with sudden large inflows",
    "AML-05": "High-velocity dispersion of funds",
    "AML-06": "Geographically impossible activity (card/account compromise)",
    "AML-07": "Money-mule collection from many unrelated senders",
    "AML-08": "Exposure to high-risk jurisdictions",
    "AML-09": "Large cash deposits",
    "AML-10": "Sudden high-volume activity on a newly opened account",
}

_REQUIRED_KEYS = {
    "executive_summary",
    "key_findings",
    "likely_behaviors",
    "risk_assessment",
    "recommended_next_steps",
}


def generate_investigation_summary(context: dict) -> dict:
    client = get_client()
    if client is not None:
        try:
            resp = client.chat.completions.create(
                model=settings.openai_model,
                messages=summary_messages(context),
                response_format={"type": "json_object"},
                temperature=0.3,
            )
            data = json.loads(resp.choices[0].message.content)
            if _REQUIRED_KEYS.issubset(data):
                data["generated_by"] = "openai"
                data["model"] = settings.openai_model
                return data
            logger.warning("OpenAI response missing keys; using template.")
        except Exception:  # noqa: BLE001
            logger.exception("OpenAI summary failed; using template.")
    return _template_summary(context)


def _template_summary(context: dict) -> dict:
    c = context["customer"]
    rules = context.get("rules", [])
    flagged = context.get("flagged_transactions", [])
    counts = context.get("counts", {})

    behaviors = [BEHAVIOR.get(r["code"], r["name"]) for r in rules]
    total_flagged_amt = sum(t["amount"] for t in flagged)
    top_amount = max((t["amount"] for t in flagged), default=0.0)
    n_flagged = counts.get("total_flagged", 0)
    monthly = c.get("expected_monthly_income") or 0.0
    band = c["risk_level"]

    # --- Executive summary (varied per subject + risk band) ---
    lead = {
        "critical": (
            f"{c['name']} presents a CRITICAL money-laundering risk and warrants "
            f"immediate escalation to the financial-crime unit."
        ),
        "high": (
            f"{c['name']} presents a HIGH money-laundering risk and should be "
            f"advanced to formal investigation."
        ),
        "medium": (
            f"{c['name']}'s account activity exhibits moderate anomalies that "
            f"warrant enhanced review and continued monitoring."
        ),
        "low": (
            f"{c['name']}'s account activity is largely consistent with the "
            f"expected customer profile, with only limited indicators noted."
        ),
    }.get(band, f"{c['name']} has been reviewed by automated monitoring.")

    parts = [
        lead,
        f"The subject is a {c['occupation']} in {c['city']}, {c['country']}, with a "
        f"declared annual income of ${c['annual_income']:,.0f} and a "
        f"{c['kyc_status']} KYC status.",
    ]
    if rules:
        rule_phrase = behaviors[0].lower()
        if len(behaviors) > 1:
            rule_phrase += f" and {behaviors[1].lower()}"
        parts.append(
            f"Transaction monitoring produced a composite risk score of "
            f"{c['risk_score']}/100, driven by {len(rules)} detection rule(s) "
            f"across {n_flagged} flagged transaction(s) totalling "
            f"${total_flagged_amt:,.0f}. The pattern is most consistent with "
            f"{rule_phrase}."
        )
        if monthly and top_amount > monthly * 3 and band in ("high", "critical"):
            parts.append(
                f"The largest flagged movement of ${top_amount:,.0f} is "
                f"approximately {top_amount / max(monthly, 1):.0f}x the subject's "
                f"expected monthly income — a material inconsistency with the "
                f"stated economic profile."
            )
    else:
        parts.append(
            f"No detection rules were triggered and the account scored "
            f"{c['risk_score']}/100; activity appears commensurate with the profile."
        )
    executive_summary = " ".join(parts)

    # --- Key findings ---
    key_findings = [
        f"{r['name']} ({r['code']}): {r['reason']}" for r in rules
    ]
    if flagged:
        key_findings.append(
            f"{n_flagged} transaction(s) were rule-flagged, totalling "
            f"${total_flagged_amt:,.0f}; the single largest was ${top_amount:,.0f}."
        )
    if c.get("is_high_risk_jurisdiction"):
        key_findings.append(
            f"The customer is domiciled in a high-risk jurisdiction ({c['country']})."
        )
    if c["kyc_status"] != "verified":
        key_findings.append(
            f"KYC verification is {c['kyc_status']}, weakening identity assurance."
        )
    if not key_findings:
        key_findings.append("No adverse findings were identified during review.")

    # --- Risk assessment ---
    risk_assessment = {
        "critical": (
            "The overall risk is assessed as CRITICAL. Several strong, mutually "
            "reinforcing indicators of coordinated laundering are present, and the "
            "activity cannot be reconciled with the customer's known profile. "
            "Immediate escalation and protective action are justified."
        ),
        "high": (
            "The overall risk is assessed as HIGH. The volume and pattern of "
            "flagged activity are materially inconsistent with the expected "
            "profile and merit a formal, documented investigation."
        ),
        "medium": (
            "The overall risk is assessed as MEDIUM. The anomalies identified are "
            "noteworthy but not yet conclusive; enhanced monitoring and analyst "
            "review are recommended before further escalation."
        ),
        "low": (
            "The overall risk is assessed as LOW. Indicators are limited and "
            "routine periodic monitoring is considered sufficient at this time."
        ),
    }.get(band, "Risk assessment unavailable.")

    # --- Recommended next steps ---
    if band in ("high", "critical"):
        next_steps = [
            "Initiate Enhanced Due Diligence (EDD) on the subject and all connected parties.",
            "Map the transaction network for linked accounts, mules, and counterparties.",
            "Prepare and file a Suspicious Activity Report (SAR) with the relevant FIU.",
        ]
        if band == "critical":
            next_steps.append(
                "Consider a temporary account restriction or hold pending review."
            )
    elif band == "medium":
        next_steps = [
            "Apply enhanced transaction monitoring for a 90-day observation window.",
            "Request supporting documentation for the flagged transactions.",
            "Re-assess the risk rating if further anomalies emerge.",
        ]
    else:
        next_steps = [
            "Maintain standard periodic monitoring.",
            "No further action is required at this time.",
        ]

    return {
        "executive_summary": executive_summary,
        "key_findings": key_findings,
        "likely_behaviors": behaviors or ["No suspicious behavior identified"],
        "risk_assessment": risk_assessment,
        "recommended_next_steps": next_steps,
        "generated_by": "template",
        "model": None,
    }
